import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { fetchMoviesByTitle } from "./api/hello";
import { useRouter } from "next/router";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  const [searchTerm, setSearchTerm] = useState("");
  const [searchedMovies, setSearchedMovies] = useState([]);
  const router = useRouter();

  const handleSearch = async () => {
    const response = await fetchMoviesByTitle(searchTerm);
    setSearchedMovies(response.Search || []);
  };

  const handleOnClick = (imdbID) => {
    router.push(`/${imdbID}`);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <header className={styles.header}>
          <h1>Movies</h1>
        </header>
        <main className={styles.main}>
          <div className={styles.inputBox}>
            <input
              type="text"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              placeholder="Search for a movie"
            />
            <button onClick={handleSearch} className={styles.button}>
              Search
            </button>
          </div>
          <div className={styles.movieItems}>
            {searchedMovies.map((movie) => (
              <div key={movie.imdbID} className={styles.movieItem}>
                <h2 className={styles.movieTitle}>{movie.Title}</h2>
                <Image
                  src={movie.Poster}
                  alt={movie.Title}
                  width={200}
                  height={300}
                />
                <button
                  onClick={() => handleOnClick(movie.imdbID)}
                  className={styles.detailsButton}
                >
                  Details
                </button>
              </div>
            ))}
          </div>
        </main>
        <footer className={styles.footer}>
          <p>Movies</p>
        </footer>
      </div>
    </>
  );
}
